<?php

namespace Database\Seeders;

use App\Models\Organization;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrganizationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $organizations = [
            ['sistem' => 'SVAWeb','status' => true, 'name' => 'Avansis Ltda.', 'company' => 'Vladimir Delic C y Cia Ltda.','rut' => '76096314-3'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Central de Carnes', 'company' => 'Central de Carnes Ltda','rut' => '77650460-2'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Arecheta', 'company' => 'Comercial Arecheta S.A','rut' => '96558780-2'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Arca Hogar', 'company' => 'Importadora Y Comercializadora Rio Serrano SPA','rut' => '77220124-9'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Cecinas Munchen', 'company' => 'Cecinas Munchen Ltda','rut' => '76849950-0'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Trasworld', 'company' => 'Transworld Supply Ltda','rut' => '77829700-0'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Sociedad Real', 'company' => 'Soc. Real Y Cia. Ltda','rut' => '76129350-8'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Emprenani', 'company' => 'Emprenani Ltda','rut' => '78795760-9'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Corcoran', 'company' => 'Corcoran Y Cia. SPA','rut' => '86527400-9'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'IMPA', 'company' => 'Ingeniería Mecánica, Proyectos y Asesorías, Limitada','rut' => '86676200-7'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Base Camp', 'company' => 'Campamento Base SPA','rut' => '76247309-7'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'MADEIN', 'company' => 'Comercial Fernardo Garcia E. I. R.L','rut' => '76411824-3'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Concrete Jungle', 'company' => 'Disenos Industriales Carolina Vukasovic Eirl','rut' => '76276671-K'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Pacifico Digital', 'company' => 'Importadora Y Comercial Pacifico Digital Spa','rut' => '76168842-1'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Ansilta', 'company' => 'Campamento SPA','rut' => '77121077-5'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Inversiones Best SPA', 'company' => 'Inversiones Best Spa','rut' => '77340697-9'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Wakool', 'company' => 'Wakool Duty Free Spa','rut' => '77487858-0'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Tienda ONE', 'company' => 'Margarita Vicente Poklepovic','rut' => '7860076-4'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'City Toys', 'company' => 'Inversiones City Play Spa','rut' => '76956891-3'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'La comarca del hobby', 'company' => 'Dante Ortiz Y Compañia Ltda','rut' => '77300385-8'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Coyote Kids', 'company' => 'Importadora Y Comerc. Sofemi Spa','rut' => '76449587-K'],
            ['sistem' => 'AvanZF','status' => true, 'name' => 'Finning', 'company' => 'Finning Chile S.A.','rut' => '91489000-4'],
            ['sistem' => 'SVAWeb','status' => true, 'name' => 'Rofil', 'company' => 'Distribucion Rofil Ltda.','rut' => '88831200-5'],
            // ['sistem' => 'SVAWeb','status' => true, 'name' => 'Sánchez', 'company' => 'Sánchez y Sánchez SpA.','rut' => '96620660-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'JOSÉ MIGUEL DURÁN DÍAZ', 'company' => 'JOSÉ MIGUEL DURÁN DÍAZ','rut' => '10767126-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Patricio David Segovia Sánchez', 'company' => 'Patricio David Segovia Sánchez','rut' => '15581798-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Pablo Iván Álvarez Curinao', 'company' => 'Pablo Iván Álvarez Curinao','rut' => '17595449-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Erasmo Enrique Reinoso Davidson', 'company' => 'Erasmo Enrique Reinoso Davidson','rut' => '5640556-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Industria Weatherford International de Chile S.A.', 'company' => 'Industria Weatherford International de Chile S.A.','rut' => '76026281-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Distribución y Logística Magallanes Ltda.', 'company' => 'Distribución y Logística Magallanes Ltda.','rut' => '76098031-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotriz Varona Ltda.', 'company' => 'Automotriz Varona Ltda.','rut' => '76101820-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'B.P.N. SpA', 'company' => 'B.P.N. SpA','rut' => '76238626-7'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Fernando García E.I.R.L. o Comercial One Chile E.I', 'company' => 'Comercial Fernando García E.I.R.L. o Comercial One Chile E.I','rut' => '76411824-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'BIKE STORE LTDA.', 'company' => 'BIKE STORE LTDA.','rut' => '76756944-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotora Varona SpA', 'company' => 'Automotora Varona SpA','rut' => '77239467-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotores Gildemeister SpA', 'company' => 'Automotores Gildemeister SpA','rut' => '79649140-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Elsa Muñoz Uribe', 'company' => 'Elsa Muñoz Uribe','rut' => '8177591-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Frada y Cía.Ltda.', 'company' => 'Comercial Frada y Cía.Ltda.','rut' => '81426100-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Camping Sur Ltda.', 'company' => 'Camping Sur Ltda.','rut' => '84789500-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Aerovías Dap S.A.', 'company' => 'Aerovías Dap S.A.','rut' => '89428000-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Dario Antonio Sepulveda Ugarte', 'company' => 'Dario Antonio Sepulveda Ugarte','rut' => '9405598-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Embotelladora Andina S.A.', 'company' => 'Embotelladora Andina S.A.','rut' => '91144000-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'General Motors Industria Automotriz Ltda.', 'company' => 'General Motors Industria Automotriz Ltda.','rut' => '93515000-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ulog Soluciones Logísticas Integrales Limitada', 'company' => 'Ulog Soluciones Logísticas Integrales Limitada','rut' => '96172570-9'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Arecheta S.A.', 'company' => 'Comercial Arecheta S.A.','rut' => '96558780-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Kaufmann S.A.', 'company' => 'Comercial Kaufmann S.A.','rut' => '96572360-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Consultora en Zona Franca S.A.', 'company' => 'Consultora en Zona Franca S.A.','rut' => '96634110-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Diva Angélica Carreño Becerra', 'company' => 'Diva Angélica Carreño Becerra','rut' => '11978812-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Oscar Francino Saldivia', 'company' => 'Eduardo Oscar Francino Saldivia','rut' => '12052858-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Enrique Hernández Sagredo', 'company' => 'Eduardo Enrique Hernández Sagredo','rut' => '12107379-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos Andrés Gallardo Ruiz', 'company' => 'Carlos Andrés Gallardo Ruiz','rut' => '13970866-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cristian Alfredo Zambrano Mercado', 'company' => 'Cristian Alfredo Zambrano Mercado','rut' => '14353087-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Dante Javier Alvarado Uribe', 'company' => 'Dante Javier Alvarado Uribe','rut' => '15309475-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cristian Andrés Velásquez Oyarzo', 'company' => 'Cristian Andrés Velásquez Oyarzo','rut' => '15310167-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos Eduardo Barría Barría', 'company' => 'Carlos Eduardo Barría Barría','rut' => '15310398-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Armando Alejandro Nuñez Parada', 'company' => 'Armando Alejandro Nuñez Parada','rut' => '15505380-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Andrés Felipe Almonacid Contreras', 'company' => 'Eduardo Andrés Felipe Almonacid Contreras','rut' => '15580171-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ariel Arnaldo Cerón Vargas', 'company' => 'Ariel Arnaldo Cerón Vargas','rut' => '15582166-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Claudio Andrés Ortiz Sagredo', 'company' => 'Claudio Andrés Ortiz Sagredo','rut' => '15670614-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Fabian Alexis Chacón Ancar', 'company' => 'Fabian Alexis Chacón Ancar','rut' => '16163387-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Edgardo Cristóbal Gallardo Nieto', 'company' => 'Edgardo Cristóbal Gallardo Nieto','rut' => '16965880-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cristian Javier Muñoz Fernández y Otros', 'company' => 'Cristian Javier Muñoz Fernández y Otros','rut' => '53306469-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alexis Edgardo Coronado Coronado', 'company' => 'Alexis Edgardo Coronado Coronado','rut' => '6493481-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eliana Edith Uribe Mancilla', 'company' => 'Eliana Edith Uribe Mancilla','rut' => '6717509-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cuerpo de Bomberos de Punta Arenas', 'company' => 'Cuerpo de Bomberos de Punta Arenas','rut' => '70005600-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Corporación Municipal de Punta Arenas', 'company' => 'Corporación Municipal de Punta Arenas','rut' => '70931900-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'A&A Servicios Especiales Ltda.', 'company' => 'A&A Servicios Especiales Ltda.','rut' => '76016513-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotora de la Patagonia Ltda.', 'company' => 'Automotora de la Patagonia Ltda.','rut' => '76017643-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora de Repuestos Arturo', 'company' => 'Comercializadora de Repuestos Arturo','rut' => '76039047-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Conexiones y Telefonía Austral Ltda.', 'company' => 'Conexiones y Telefonía Austral Ltda.','rut' => '76089501-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Construcciones y Obras Miguel Alejandro', 'company' => 'Construcciones y Obras Miguel Alejandro','rut' => '76093577-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eventos Guillermina Gallardo Soto E.I.R.L.', 'company' => 'Eventos Guillermina Gallardo Soto E.I.R.L.','rut' => '76136112-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Edelweiss SpA. o Distribuidora Edelweiss', 'company' => 'Edelweiss SpA. o Distribuidora Edelweiss','rut' => '76145364-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Arriendo de Vehículos y Agencia de Viajes', 'company' => 'Arriendo de Vehículos y Agencia de Viajes','rut' => '76147812-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Todo Acero Ltda.', 'company' => 'Comercial Todo Acero Ltda.','rut' => '76148754-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'A&A Servicios E.I.R.L.', 'company' => 'A&A Servicios E.I.R.L.','rut' => '76159097-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotriz e Inversiones del Sur Ltda.', 'company' => 'Automotriz e Inversiones del Sur Ltda.','rut' => '76176308-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora y Servicios Mecanicos', 'company' => 'Comercializadora y Servicios Mecanicos','rut' => '76182295-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Bioingeniería y Gestión Global Ltda.', 'company' => 'Bioingeniería y Gestión Global Ltda.','rut' => '76192078-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Patagonia Gourmet & Delivery', 'company' => 'Comercial Patagonia Gourmet & Delivery','rut' => '76226753-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Duty Free del Estrecho Ltda.', 'company' => 'Duty Free del Estrecho Ltda.','rut' => '76233916-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Agencia Inés E.I.R.L.', 'company' => 'Agencia Inés E.I.R.L.','rut' => '76235408-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Almacen Jessica Muñoz Caipillan SpA', 'company' => 'Almacen Jessica Muñoz Caipillan SpA','rut' => '76293591-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Concremag S.A.', 'company' => 'Concremag S.A.','rut' => '76301094-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora HMF Motor S', 'company' => 'Comercial e Importadora HMF Motor S','rut' => '76311798-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial CJ E.I.R.L.', 'company' => 'Comercial CJ E.I.R.L.','rut' => '76322433-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automoviles E y E Ltda.', 'company' => 'Automoviles E y E Ltda.','rut' => '76374624-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alpha Energy S.A.', 'company' => 'Alpha Energy S.A.','rut' => '76413715-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora Panama Sur Ltda. o', 'company' => 'Comercializadora Panama Sur Ltda. o','rut' => '76417282-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'BM Inspecciones SpA', 'company' => 'BM Inspecciones SpA','rut' => '76455814-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ebcosur S.A.', 'company' => 'Ebcosur S.A.','rut' => '76525290-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Estrella Petrolera de Chile S.A.', 'company' => 'Estrella Petrolera de Chile S.A.','rut' => '76560450-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora Top Car Parts Ltda.', 'company' => 'Comercializadora Top Car Parts Ltda.','rut' => '76561467-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Arriendo e Importacion de Vehiculos M', 'company' => 'Arriendo e Importacion de Vehiculos M','rut' => '76665102-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Exterran Energy Solutions Cía. Ltda.', 'company' => 'Exterran Energy Solutions Cía. Ltda.','rut' => '76682950-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora Laza S.A.', 'company' => 'Comercializadora Laza S.A.','rut' => '76685070-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Boutique y Estética, Sesasi y Compañía', 'company' => 'Boutique y Estética, Sesasi y Compañía','rut' => '76714099-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Centro Logístico Kaweskar Importadora', 'company' => 'Centro Logístico Kaweskar Importadora','rut' => '76755241-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Alpha Ltda.', 'company' => 'Comercial Alpha Ltda.','rut' => '76780325-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Administradora El Horreo Ltda.', 'company' => 'Administradora El Horreo Ltda.','rut' => '76790063-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Buses Patagonia SpA.', 'company' => 'Buses Patagonia SpA.','rut' => '76823066-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Bebidas y Alcoholes Marion Garcia Lop', 'company' => 'Bebidas y Alcoholes Marion Garcia Lop','rut' => '76913900-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial San Marcos SpA', 'company' => 'Comercial San Marcos SpA','rut' => '76991593-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora Helser Limitada', 'company' => 'Comercializadora Helser Limitada','rut' => '77156581-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Camex Automotriz SpA.', 'company' => 'Camex Automotriz SpA.','rut' => '77223211-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ferremundo SpA', 'company' => 'Ferremundo SpA','rut' => '77223826-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'American Power SpA', 'company' => 'American Power SpA','rut' => '77229363-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ama SpA', 'company' => 'Ama SpA','rut' => '77282623-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Aile Importadora SpA.', 'company' => 'Aile Importadora SpA.','rut' => '77405479-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora y Distribuidora Alsol', 'company' => 'Comercializadora y Distribuidora Alsol','rut' => '78968260-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Gomplas Ltda.', 'company' => 'Comercial Gomplas Ltda.','rut' => '78996240-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cía. de Comercio y Desarrollo Pesquera', 'company' => 'Cía. de Comercio y Desarrollo Pesquera','rut' => '79693780-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'El Arte de Vestir S.A', 'company' => 'El Arte de Vestir S.A','rut' => '79862960-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Arturo Alex Zúñiga Agoni', 'company' => 'Arturo Alex Zúñiga Agoni','rut' => '8075386-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eugenio Alejandro Atala Mathieu', 'company' => 'Eugenio Alejandro Atala Mathieu','rut' => '8305189-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alejandro Segundo Cárdenas Burgos', 'company' => 'Alejandro Segundo Cárdenas Burgos','rut' => '8721817-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Empresa Constructora Bravo e Izquierdo', 'company' => 'Empresa Constructora Bravo e Izquierdo','rut' => '84102200-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Emilio Salles e Hijos Ltda.', 'company' => 'Emilio Salles e Hijos Ltda.','rut' => '87754400-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Javier Villegas Bahamonde', 'company' => 'Eduardo Javier Villegas Bahamonde','rut' => '9527492-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Danilo Mauricio Mancilla Ruiz', 'company' => 'Danilo Mauricio Mancilla Ruiz','rut' => '9659083-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'David Fernando Masferrer Ostoloza', 'company' => 'David Fernando Masferrer Ostoloza','rut' => '9909124-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Conglomerantes y Cales de Chile S.A.', 'company' => 'Conglomerantes y Cales de Chile S.A.','rut' => '96890520-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Banco de Crédito e Inversiones', 'company' => 'Banco de Crédito e Inversiones','rut' => '97006000-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comunicaciones Austral y Compañía Ltda.', 'company' => 'Comunicaciones Austral y Compañía Ltda.','rut' => '76192736-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Constructora Austral SpA.', 'company' => 'Constructora Austral SpA.','rut' => '76468833-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Bellapatagonia Ltda.', 'company' => 'Comercial Bellapatagonia Ltda.','rut' => '76549950-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlev Ltda.', 'company' => 'Carlev Ltda.','rut' => '76478877-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Astilleros y Servicios Industriales Ltda.', 'company' => 'Astilleros y Servicios Industriales Ltda.','rut' => '78158110-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ernesto García Lein', 'company' => 'Ernesto García Lein','rut' => '4070003-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cristian Mario Bustos Coronado', 'company' => 'Cristian Mario Bustos Coronado','rut' => '14042795-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'América Yanett Mimica Cárdenas', 'company' => 'América Yanett Mimica Cárdenas','rut' => '7617470-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Empresa de Transporte Sergio Fabián Aravena Abarzúa E.I.R.L.', 'company' => 'Empresa de Transporte Sergio Fabián Aravena Abarzúa E.I.R.L.','rut' => '76401754-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Claudio Andrés Correa Barahona', 'company' => 'Claudio Andrés Correa Barahona','rut' => '12103974-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Baudillo Ceballos Martínez', 'company' => 'Eduardo Baudillo Ceballos Martínez','rut' => '12125439-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Enzo Daniel Paredes Nahuelquin', 'company' => 'Enzo Daniel Paredes Nahuelquin','rut' => '13740147-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carolina de Lourdes Benavente Gómez', 'company' => 'Carolina de Lourdes Benavente Gómez','rut' => '13792544-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Esteban Alberto Canales Sagredo', 'company' => 'Esteban Alberto Canales Sagredo','rut' => '14333692-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Elizabeth Noeline Barkla', 'company' => 'Elizabeth Noeline Barkla','rut' => '23071845-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Aladin Bruno Villar Rosas', 'company' => 'Aladin Bruno Villar Rosas','rut' => '6439425-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Agrícola El Encuentro Ltda.', 'company' => 'Agrícola El Encuentro Ltda.','rut' => '76034325-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotriz Sergio Ignacio Gaete Toro E.I.R.L.', 'company' => 'Automotriz Sergio Ignacio Gaete Toro E.I.R.L.','rut' => '76394594-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'B&E Patagonia SpA', 'company' => 'B&E Patagonia SpA','rut' => '77387313-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carolina Ana del Carmen Zambrano Cubilla', 'company' => 'Carolina Ana del Carmen Zambrano Cubilla','rut' => '8095697-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Erika del Carmen Cid Medina', 'company' => 'Erika del Carmen Cid Medina','rut' => '8260276-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Evaristo Daniel Cedas Colivoro', 'company' => 'Evaristo Daniel Cedas Colivoro','rut' => '8679001-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos Omar Seguel Márquez', 'company' => 'Carlos Omar Seguel Márquez','rut' => '8727866-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotora Comercial Costabal y Echeñique S.A.', 'company' => 'Automotora Comercial Costabal y Echeñique S.A.','rut' => '91139000-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotora Sin Límites Ltda.', 'company' => 'Automotora Sin Límites Ltda.','rut' => '76557647-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cesar Antonio Rubilar Sanhueza', 'company' => 'Cesar Antonio Rubilar Sanhueza','rut' => '16312639-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alvaro Cristián Hormazábal López', 'company' => 'Alvaro Cristián Hormazábal López','rut' => '12264357-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Bodega del Sur SpA.', 'company' => 'Bodega del Sur SpA.','rut' => '77129738-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'América Chile Comercializadora Ltda.', 'company' => 'América Chile Comercializadora Ltda.','rut' => '24235374-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Drager Medical Chile Ltda.', 'company' => 'Drager Medical Chile Ltda.','rut' => '76033880-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Datamédica S.A.', 'company' => 'Datamédica S.A.','rut' => '76046685-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Centro Global de Energía Sustentable Consultoría y Asesoría Ltda.', 'company' => 'Centro Global de Energía Sustentable Consultoría y Asesoría Ltda.','rut' => '76091335-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Asiamotors SpA.', 'company' => 'Asiamotors SpA.','rut' => '76115163-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Austral Importadora y Exportadora SpA.', 'company' => 'Austral Importadora y Exportadora SpA.','rut' => '76270856-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Agencias Internacionales S.A.', 'company' => 'Agencias Internacionales S.A.','rut' => '76824390-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Adasme y Cía. Ltda.', 'company' => 'Adasme y Cía. Ltda.','rut' => '77598630-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Epysa Buses Ltda.', 'company' => 'Epysa Buses Ltda.','rut' => '77824870-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Mundo LCV Ltda.', 'company' => 'Comercial Mundo LCV Ltda.','rut' => '77869040-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Celestron Representaciones Comerciales Internacionales e Inversiones', 'company' => 'Celestron Representaciones Comerciales Internacionales e Inversiones','rut' => '78729990-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Bertonati Vehiculos Especiales Ltda.', 'company' => 'Bertonati Vehiculos Especiales Ltda.','rut' => '87927900-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos Nazar Representaciones S.A.', 'company' => 'Carlos Nazar Representaciones S.A.','rut' => '96540270-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial y Distribuidora Bertonati S.A.', 'company' => 'Comercial y Distribuidora Bertonati S.A.','rut' => '96825800-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cavas Reunidas S.A.', 'company' => 'Cavas Reunidas S.A.','rut' => '96856980-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Conversiones San José Ltda.', 'company' => 'Conversiones San José Ltda.','rut' => '96981470-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Compañía de Petroleos de Chile Copec S.A.', 'company' => 'Compañía de Petroleos de Chile Copec S.A.','rut' => '99520000-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Computación Portátil Chile S.A.', 'company' => 'Computación Portátil Chile S.A.','rut' => '99548870-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Airtech Ltda.', 'company' => 'Airtech Ltda.','rut' => '76167580-k'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Computación Integral S.A.', 'company' => 'Computación Integral S.A.','rut' => '96689970-0'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercial Pacífico Digital Ltda.', 'company' => 'Importadora y Comercial Pacífico Digital Ltda.','rut' => '76168842-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'AR Logistics SpA.', 'company' => 'AR Logistics SpA.','rut' => '76742019-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Astilleros y Maestranzas de la Armada', 'company' => 'Astilleros y Maestranzas de la Armada','rut' => '61106000-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Bovogi SpA', 'company' => 'Bovogi SpA','rut' => '76973894-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Chillean Satellite Ground', 'company' => 'Chillean Satellite Ground','rut' => '76693052-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Codimaga', 'company' => 'Codimaga','rut' => '81500000-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Com. Bharatmal Bassarmal Mayaramani SAC', 'company' => 'Com. Bharatmal Bassarmal Mayaramani SAC','rut' => '76293270-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'COM. STEEL HOME BUILDING CHILE', 'company' => 'COM. STEEL HOME BUILDING CHILE','rut' => '77170080-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial AVM Importaciones SpA', 'company' => 'Comercial AVM Importaciones SpA','rut' => '76585304-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Central Point', 'company' => 'Comercial Central Point','rut' => '76661050-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'COMERCIAL DE LA PATAGONIA LTDA.', 'company' => 'COMERCIAL DE LA PATAGONIA LTDA.','rut' => '78578780-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora Victor Alejandro Vargas', 'company' => 'Comercial e Importadora Victor Alejandro Vargas','rut' => '77277597-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Siromax Spa.', 'company' => 'Comercial Siromax Spa.','rut' => '76047492-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Mardel Ltda.', 'company' => 'Comercial Mardel Ltda.','rut' => '84523500-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'DISTRIBUIDORA LAS LECHUZAS LIMITADA', 'company' => 'DISTRIBUIDORA LAS LECHUZAS LIMITADA','rut' => '77551580-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'EDUARDO ESTEBAN BARRIA VILLARROEL', 'company' => 'EDUARDO ESTEBAN BARRIA VILLARROEL','rut' => '15307729-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'COMER. EL RINCON GANADERO', 'company' => 'COMER. EL RINCON GANADERO','rut' => '76223837-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'FERRETERIA EL AGUILA SPA', 'company' => 'FERRETERIA EL AGUILA SPA','rut' => '83957900-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'GEOPARK FELL SPA', 'company' => 'GEOPARK FELL SPA','rut' => '76129094-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'HECTOR FREDY MUÑOZ MANCILLA', 'company' => 'HECTOR FREDY MUÑOZ MANCILLA','rut' => '12541709-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'HK IMPORTACIONES LIMITADA', 'company' => 'HK IMPORTACIONES LIMITADA','rut' => '76747451-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Horacio Boccazzi y Otros', 'company' => 'Importaciones Horacio Boccazzi y Otros','rut' => '77274895-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'IMPORTACIONES USAJ EIRL', 'company' => 'IMPORTACIONES USAJ EIRL','rut' => '76354504-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones de Vehículos Motorizados, Repuestos y Accesorios Vengas y Mancilla Ltda.', 'company' => 'Importaciones de Vehículos Motorizados, Repuestos y Accesorios Vengas y Mancilla Ltda.','rut' => '77100138-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Suiza', 'company' => 'Importadora Suiza','rut' => '95087000-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'IMPORTADORA V&S', 'company' => 'IMPORTADORA V&S','rut' => '77238012-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Inversiones Las Arenas', 'company' => 'Inversiones Las Arenas','rut' => '77297280-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'JORGE LUIS MAMANI LAURA', 'company' => 'JORGE LUIS MAMANI LAURA','rut' => '24260240-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'JOSE AGUSTIN OLATE SANCHEZ', 'company' => 'JOSE AGUSTIN OLATE SANCHEZ','rut' => '12653297-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'José Domingo Caldichoury Rios', 'company' => 'José Domingo Caldichoury Rios','rut' => '4595593-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'José Luis Bobadilla Sepulveda', 'company' => 'José Luis Bobadilla Sepulveda','rut' => '15467094-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'JOSE MIGUEL JARA BUSTAMANTE', 'company' => 'JOSE MIGUEL JARA BUSTAMANTE','rut' => '14229604-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Logistica e Ingenieria Agroveterinaria Ltda', 'company' => 'Logistica e Ingenieria Agroveterinaria Ltda','rut' => '76310702-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'National Oilwell Varco de Chile - Servicios Limitada', 'company' => 'National Oilwell Varco de Chile - Servicios Limitada','rut' => '76136709-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'ORGANIZACIÓN JOLLY LTDA', 'company' => 'ORGANIZACIÓN JOLLY LTDA','rut' => '85041400-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Outdoors Patagonia SpA', 'company' => 'Outdoors Patagonia SpA','rut' => '76802057-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'SALINAS Y FABRES S.A', 'company' => 'SALINAS Y FABRES S.A','rut' => '91502000-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sergio Pablo Lara Baez', 'company' => 'Sergio Pablo Lara Baez','rut' => '12428336-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'SERGIO TRIVIÑO SIERPE E.I.R.L', 'company' => 'SERGIO TRIVIÑO SIERPE E.I.R.L','rut' => '52000776-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'SOC. DE ING. Y SERVICIOS HOGG Y SERRANO LTDA.', 'company' => 'SOC. DE ING. Y SERVICIOS HOGG Y SERRANO LTDA.','rut' => '79555420-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'SOC. COM. INAL Y CIA. LTDA.', 'company' => 'SOC. COM. INAL Y CIA. LTDA.','rut' => '77844340-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'TAU PERFORACIONES SPA', 'company' => 'TAU PERFORACIONES SPA','rut' => '77034992-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'BALBOTIN Y FERNANDEZ LIMITADA', 'company' => 'BALBOTIN Y FERNANDEZ LIMITADA','rut' => '85034800-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Transbordadora Austral Broom S.A.', 'company' => 'Transbordadora Austral Broom S.A.','rut' => '82074900-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Luis Roberto Gonzalez Guzmán', 'company' => 'Luis Roberto Gonzalez Guzmán','rut' => '6523170-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'AES Ltda', 'company' => 'AES Ltda','rut' => '78304900-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Marcos Antonio Mopovic Torres', 'company' => 'Marcos Antonio Mopovic Torres','rut' => '8078750-2'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercializadora Río Serrano SpA', 'company' => 'Importadora y Comercializadora Río Serrano SpA','rut' => '77220124-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos José Vivar Rivera', 'company' => 'Carlos José Vivar Rivera','rut' => '5597671-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Robinson Andrés Casanova Farfán', 'company' => 'Robinson Andrés Casanova Farfán','rut' => '12725907-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Impresos Vanic Ltda.', 'company' => 'Impresos Vanic Ltda.','rut' => '89202400-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Music Center ZF SpA.', 'company' => 'Music Center ZF SpA.','rut' => '76363690-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Areas Verdes Ltda.', 'company' => 'Areas Verdes Ltda.','rut' => '79521580-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Eduardo Oscar Laibe Vera', 'company' => 'Eduardo Oscar Laibe Vera','rut' => '7872687-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'José Hugo Oyarzo Zuñiga', 'company' => 'José Hugo Oyarzo Zuñiga','rut' => '5234037-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'María Luisa Chamorro Cárdenas', 'company' => 'María Luisa Chamorro Cárdenas','rut' => '7139604-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'David Nacor Opazo Barraza', 'company' => 'David Nacor Opazo Barraza','rut' => '9472097-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Martin Luksic Gasic E.I.R.L.', 'company' => 'Comercial Martin Luksic Gasic E.I.R.L.','rut' => '76720875-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Mundo Vape SpA', 'company' => 'Mundo Vape SpA','rut' => '76980302-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Luis Armando Sebastian Barrientos Gómez', 'company' => 'Luis Armando Sebastian Barrientos Gómez','rut' => '17587275-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones CM SpA', 'company' => 'Importaciones CM SpA','rut' => '77370466-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'The Cars Live', 'company' => 'The Cars Live','rut' => '76384262-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Inversiones Bilbao SpA', 'company' => 'Inversiones Bilbao SpA','rut' => '77112612-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial García Marinkovic Limitada', 'company' => 'Comercial García Marinkovic Limitada','rut' => '76012387-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cabezales del Sur SpA', 'company' => 'Cabezales del Sur SpA','rut' => '76310109-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Carlos Ernesto Cardenas Sanchez', 'company' => 'Carlos Ernesto Cardenas Sanchez','rut' => '13123292-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Celso Juvenal Castro Villarroel', 'company' => 'Celso Juvenal Castro Villarroel','rut' => '7965622-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'CLAUDIA KARINA RIVERA DANYAU', 'company' => 'CLAUDIA KARINA RIVERA DANYAU','rut' => '76671474-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Díaz Hermanos Ltda.', 'company' => 'Comercial Díaz Hermanos Ltda.','rut' => '51016740-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora Cristian Cea Fuentes E.I.R.L', 'company' => 'Comercial e Importadora Cristian Cea Fuentes E.I.R.L','rut' => '76533908-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora Gonzalo Alejandro Marquez Maldonado', 'company' => 'Comercial e Importadora Gonzalo Alejandro Marquez Maldonado','rut' => '76595675-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora JJTT SpA', 'company' => 'Comercial e Importadora JJTT SpA','rut' => '77154377-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Inversiones Crosur Ltda', 'company' => 'Comercial e Inversiones Crosur Ltda','rut' => '78197550-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial y Representaciones Petrolink Ltda', 'company' => 'Comercial y Representaciones Petrolink Ltda','rut' => '78560840-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Jose Raul Hueichacoe Bahamondez', 'company' => 'Jose Raul Hueichacoe Bahamondez','rut' => '8087722-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora Solargas SpA', 'company' => 'Comercializadora Solargas SpA','rut' => '76315947-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercio Exterior y Logística Patagonia SpA.', 'company' => 'Comercio Exterior y Logística Patagonia SpA.','rut' => '76894319-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Juan Santiago Soto Mac-Lean', 'company' => 'Juan Santiago Soto Mac-Lean','rut' => '10908024-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Dap Helicopteros Ltda.', 'company' => 'Dap Helicopteros Ltda.','rut' => '78880210-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Julia Ester Mansilla Aguila', 'company' => 'Julia Ester Mansilla Aguila','rut' => '13324823-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Deportes Sparta SpA', 'company' => 'Deportes Sparta SpA','rut' => '76074938-9'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Distribucion Rofil Ltda.', 'company' => 'Distribucion Rofil Ltda.','rut' => '88831200-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Empresa Electrica de Magallanes S.A.', 'company' => 'Empresa Electrica de Magallanes S.A.','rut' => '88221200-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Empresa Nacional del Petroleo', 'company' => 'Empresa Nacional del Petroleo','rut' => '92604000-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora L.G.M. Ltda.', 'company' => 'Importadora L.G.M. Ltda.','rut' => '76681667-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Import A y M Asociados SpA', 'company' => 'Import A y M Asociados SpA','rut' => '76887383-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Carlos Antonio Polanco Alderete E.I.R.L.', 'company' => 'Importaciones Carlos Antonio Polanco Alderete E.I.R.L.','rut' => '76809458-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Godoy y Cáceres Ltda.', 'company' => 'Importaciones Godoy y Cáceres Ltda.','rut' => '77102521-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones y Exportaciones Araya Cars y Cía. Ltda.', 'company' => 'Importaciones y Exportaciones Araya Cars y Cía. Ltda.','rut' => '76535109-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Eliberto Rodrigo Muñoz Bahamonde E.I.R.L.', 'company' => 'Importadora Eliberto Rodrigo Muñoz Bahamonde E.I.R.L.','rut' => '77039637-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Fastcars Punta Arenas SpA.', 'company' => 'Importadora Fastcars Punta Arenas SpA.','rut' => '76891874-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Luis Erazo Vargas', 'company' => 'Luis Erazo Vargas','rut' => '16636531-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora New Ark Ltda.', 'company' => 'Importadora New Ark Ltda.','rut' => '76244740-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Manuel Fernando Aguila Barria', 'company' => 'Manuel Fernando Aguila Barria','rut' => '8148978-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercializadora Edison Manuel Mansilla Chávez E.I.R.L.', 'company' => 'Importadora y Comercializadora Edison Manuel Mansilla Chávez E.I.R.L.','rut' => '76277432-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Marcelo Antonio Lobrin Muñoz', 'company' => 'Marcelo Antonio Lobrin Muñoz','rut' => '8633940-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercial Salfa SpA.', 'company' => 'Importadora y Comercial Salfa SpA.','rut' => '77092722-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Exportadora San Diego Ltda.', 'company' => 'Importadora y Exportadora San Diego Ltda.','rut' => '76620388-4'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Margarita Vicente Poklepovic', 'company' => 'Margarita Vicente Poklepovic','rut' => '7860076-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Imprenta Rasmussen Ltda.', 'company' => 'Imprenta Rasmussen Ltda.','rut' => '79866170-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Mattel Chile S.A.', 'company' => 'Mattel Chile S.A.','rut' => '95877000-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Methanex Chile SpA.', 'company' => 'Methanex Chile SpA.','rut' => '76030472-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Mladinic Automotriz Ltda.', 'company' => 'Mladinic Automotriz Ltda.','rut' => '89533300-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Nicolás Andrés García Martínez', 'company' => 'Nicolás Andrés García Martínez','rut' => '18551512-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Orlov Luis Adolfo Dubrock Castañeda', 'company' => 'Orlov Luis Adolfo Dubrock Castañeda','rut' => '5408473-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Patricia del Carmen Martínez Guajardo', 'company' => 'Patricia del Carmen Martínez Guajardo','rut' => '8544540-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Pedro Alonso Chacón Saavedra E.I.R.L.', 'company' => 'Importaciones Pedro Alonso Chacón Saavedra E.I.R.L.','rut' => '76799204-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Pedro Iván Buvinic López', 'company' => 'Pedro Iván Buvinic López','rut' => '10967265-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'PSA CHILE S.A', 'company' => 'PSA CHILE S.A','rut' => '84687500-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sandy Point Importadora y Exportadora Ltda.', 'company' => 'Sandy Point Importadora y Exportadora Ltda.','rut' => '85946100-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sergio Manuel Vargas Castillo, Usuario Zona Franca E.I.R.L.', 'company' => 'Sergio Manuel Vargas Castillo, Usuario Zona Franca E.I.R.L.','rut' => '77074722-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Servifranca SpA', 'company' => 'Servifranca SpA','rut' => '77283383-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Stive Kevin Valenzuela Leon', 'company' => 'Stive Kevin Valenzuela Leon','rut' => '25999761-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Exportadora  Universal Supply Ltda.', 'company' => 'Importadora y Exportadora  Universal Supply Ltda.','rut' => '79922010-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Víctor Hugo Muñoz Sofjer', 'company' => 'Víctor Hugo Muñoz Sofjer','rut' => '15371446-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Zofra, Zona Franca Región de Aysén SpA', 'company' => 'Zofra, Zona Franca Región de Aysén SpA','rut' => '77208592-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Exportadora Andigraf Ltda.', 'company' => 'Importadora y Exportadora Andigraf Ltda.','rut' => '96582200-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Industria Frigorifica Simunovic S.A', 'company' => 'Industria Frigorifica Simunovic S.A','rut' => '91730000-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial y Automotora Integracion Austral Ltda.', 'company' => 'Comercial y Automotora Integracion Austral Ltda.','rut' => '76685440-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Julio Alejandro Rivas Inostroza', 'company' => 'Julio Alejandro Rivas Inostroza','rut' => '8499143-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'SK Car Chile Ltda.', 'company' => 'SK Car Chile Ltda.','rut' => '76414846-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Soc. de Rentas Inmobiliarias Ltda.', 'company' => 'Soc. de Rentas Inmobiliarias Ltda.','rut' => '78648070-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cesar Augusto Lombroni', 'company' => 'Cesar Augusto Lombroni','rut' => '14609320-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Manuel Alejandro Ulloa Gómez', 'company' => 'Manuel Alejandro Ulloa Gómez','rut' => '11693209-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Mauricio Javier Pérez Gómez', 'company' => 'Mauricio Javier Pérez Gómez','rut' => '12716513-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Esteban Guic y Cía. Ltda.', 'company' => 'Esteban Guic y Cía. Ltda.','rut' => '82120600-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Lomas Lindas SpA.', 'company' => 'Lomas Lindas SpA.','rut' => '76753663-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Grupo Bios S.A.', 'company' => 'Grupo Bios S.A.','rut' => '96540690-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotora Chaitén SpA.', 'company' => 'Automotora Chaitén SpA.','rut' => '76952904-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automall Punta Arenas', 'company' => 'Automall Punta Arenas','rut' => '77017817-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Orthomed Ltda.', 'company' => 'Orthomed Ltda.','rut' => '78921550-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alejandra Lorena Ruiz Ruiz', 'company' => 'Alejandra Lorena Ruiz Ruiz','rut' => '12001892-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Buses Fernández Ltda.', 'company' => 'Buses Fernández Ltda.','rut' => '77492710-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Juan Carlos Messina', 'company' => 'Juan Carlos Messina','rut' => '14705499-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Macarena Viviana Aguila Hernández', 'company' => 'Macarena Viviana Aguila Hernández','rut' => '16066236-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Morgan International Ltda.', 'company' => 'Comercial Morgan International Ltda.','rut' => '76211613-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Import-Export Pak Trading Ltda.', 'company' => 'Import-Export Pak Trading Ltda.','rut' => '76487752-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alejandro Antonio Gutiérrez Pérez', 'company' => 'Alejandro Antonio Gutiérrez Pérez','rut' => '13971342-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Comercial Casa Laibe y Compañía Ltda.', 'company' => 'Sociedad Comercial Casa Laibe y Compañía Ltda.','rut' => '79553780-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Lorenzo Mauricio Lobos Hernández', 'company' => 'Lorenzo Mauricio Lobos Hernández','rut' => '12972698-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Soc. Comercial Impex Ltda.', 'company' => 'Soc. Comercial Impex Ltda.','rut' => '79747870-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Abu Gosh y Cía Ltda.', 'company' => 'Abu Gosh y Cía Ltda.','rut' => '85641200-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora de Tabacos Austral Ltda.', 'company' => 'Importadora de Tabacos Austral Ltda.','rut' => '76765757-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Terra Australis S.A.', 'company' => 'Importadora Terra Australis S.A.','rut' => '93761000-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Jordan S.A.', 'company' => 'Jordan S.A.','rut' => '96923660-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sánchez y Sánchez SpA.', 'company' => 'Sánchez y Sánchez SpA.','rut' => '96620660-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Soc. Comercio Exterior Memo Punta Arenas SpA', 'company' => 'Soc. Comercio Exterior Memo Punta Arenas SpA','rut' => '79697160-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Camflo SpA', 'company' => 'Camflo SpA','rut' => '77174648-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Guillermo Antonio Maldonado Osorio', 'company' => 'Guillermo Antonio Maldonado Osorio','rut' => '7979318-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Pascual Jose Cambarieri', 'company' => 'Pascual Jose Cambarieri','rut' => '14666138-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sima Consultora y Asesorías Ltda.', 'company' => 'Sima Consultora y Asesorías Ltda.','rut' => '76143463-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Philips Chilena S.A.', 'company' => 'Philips Chilena S.A.','rut' => '90761000-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Agrícola y Ganadera Morro Chico Ltda.', 'company' => 'Agrícola y Ganadera Morro Chico Ltda.','rut' => '79712340-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'LGO SpA', 'company' => 'LGO SpA','rut' => '77282622-2'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercializadora Sofemi SpA.', 'company' => 'Importadora y Comercializadora Sofemi SpA.','rut' => '76449587-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Brandt E.I.R.L.', 'company' => 'Comercial Brandt E.I.R.L.','rut' => '76027456-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Distribución y Excelencia S.A.', 'company' => 'Distribución y Excelencia S.A.','rut' => '96568970-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Perkin Elmer Chile Ltda.', 'company' => 'Perkin Elmer Chile Ltda.','rut' => '77116540-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Antarctic Gate SpA.', 'company' => 'Antarctic Gate SpA.','rut' => '77468171-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Automotriz Montino SpA', 'company' => 'Automotriz Montino SpA','rut' => '77514468-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial e Importadora Koke Imports SpA', 'company' => 'Comercial e Importadora Koke Imports SpA','rut' => '77483418-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora de Autos Ltda.', 'company' => 'Comercializadora de Autos Ltda.','rut' => '76682344-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercializadora y Distribuidora a Tu Medida SpA', 'company' => 'Comercializadora y Distribuidora a Tu Medida SpA','rut' => '77141469-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Felipe Andrés Mancilla Martínez', 'company' => 'Felipe Andrés Mancilla Martínez','rut' => '18217754-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Rosario Muñoz E.I.R.L.', 'company' => 'Importaciones Rosario Muñoz E.I.R.L.','rut' => '77574654-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Borquez y Cia Ltda.', 'company' => 'Importadora Borquez y Cia Ltda.','rut' => '76417720-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'John Patrick Mestre Cayuno', 'company' => 'John Patrick Mestre Cayuno','rut' => '18208308-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'JS Velasquez SpA', 'company' => 'JS Velasquez SpA','rut' => '77365738-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'NK Patagonia Store SpA', 'company' => 'NK Patagonia Store SpA','rut' => '76990462-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ooshooia Internacional Group SpA.', 'company' => 'Ooshooia Internacional Group SpA.','rut' => '77631711-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Pamela Victoria Rivas Fica', 'company' => 'Pamela Victoria Rivas Fica','rut' => '18742356-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'PCR Trading S.A.', 'company' => 'PCR Trading S.A.','rut' => '99529880-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Servicios Pels Patagonia Express Logistics and Services Ltda.', 'company' => 'Servicios Pels Patagonia Express Logistics and Services Ltda.','rut' => '77460381-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => "Shacketon's Way Agente de Naves Limitada", 'company' => "Shacketon's Way Agente de Naves Limitada",'rut' => '76631726-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Comercial Lobos Importaciones Limitada', 'company' => 'Sociedad Comercial Lobos Importaciones Limitada','rut' => '77396626-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Top Brands International Chile S.A.', 'company' => 'Top Brands International Chile S.A.','rut' => '76154494-2'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Wakool Duty Free SpA', 'company' => 'Wakool Duty Free SpA','rut' => '77487858-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Servicios Integrales Beatriz Alvarado M. SpA', 'company' => 'Servicios Integrales Beatriz Alvarado M. SpA','rut' => '77055192-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Dannat SpA.', 'company' => 'Importaciones Dannat SpA.','rut' => '77571789-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Dalicars SpA', 'company' => 'Dalicars SpA','rut' => '77502329-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Exportadora Discount Cars Patagonia SpA.', 'company' => 'Importadora y Exportadora Discount Cars Patagonia SpA.','rut' => '77573597-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Comercial Vicam Ltda.', 'company' => 'Sociedad Comercial Vicam Ltda.','rut' => '76010961-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Servicios Manuel Luis Muñoz Guineo E.I.R.L. o Serv. Integrales Magallanes E.I.R.L.', 'company' => 'Servicios Manuel Luis Muñoz Guineo E.I.R.L. o Serv. Integrales Magallanes E.I.R.L.','rut' => '76132412-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Maximiliano Alfredo Reyes Osorio', 'company' => 'Maximiliano Alfredo Reyes Osorio','rut' => '16629071-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Marcelo Iván Mansilla Herrera', 'company' => 'Marcelo Iván Mansilla Herrera','rut' => '10246544-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Miguel Angel Cuevas Beltrán', 'company' => 'Miguel Angel Cuevas Beltrán','rut' => '15503404-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Alpha Wolf SpA', 'company' => 'Importaciones Alpha Wolf SpA','rut' => '77649056-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Z Austral SpA', 'company' => 'Importadora Z Austral SpA','rut' => '77389642-9'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Inversiones City Play SpA.', 'company' => 'Inversiones City Play SpA.','rut' => '76956891-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Peter Basurto Taramona', 'company' => 'Peter Basurto Taramona','rut' => '23246072-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Altarez SpA.', 'company' => 'Importadora Altarez SpA.','rut' => '77623361-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Tecnología e Instrumentación Dertec SpA', 'company' => 'Tecnología e Instrumentación Dertec SpA','rut' => '76050903-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Universidad de Magallanes', 'company' => 'Universidad de Magallanes','rut' => '71133700-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Lincam SpA', 'company' => 'Lincam SpA','rut' => '77153217-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Sergio Alejandro Riquelme Venegas ó Tienda Casa Amarilla Metal Rock E.I.R.L.', 'company' => 'Comercial Sergio Alejandro Riquelme Venegas ó Tienda Casa Amarilla Metal Rock E.I.R.L.','rut' => '76133701-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Austral Glass Limitada', 'company' => 'Austral Glass Limitada','rut' => '76640387-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Mario Antonio Hormazábal Montenegro', 'company' => 'Mario Antonio Hormazábal Montenegro','rut' => '14027792-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'José Osvaldo Nauto Torres', 'company' => 'José Osvaldo Nauto Torres','rut' => '8162969-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Austral Limitada', 'company' => 'Importadora Austral Limitada','rut' => '77403237-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Comercial Aries Ltda.', 'company' => 'Sociedad Comercial Aries Ltda.','rut' => '76542669-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Servicios Integrales Balkan Ltda.', 'company' => 'Servicios Integrales Balkan Ltda.','rut' => '76223115-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Panadería Sebastián Cordero J E.I.R.L.', 'company' => 'Panadería Sebastián Cordero J E.I.R.L.','rut' => '76916378-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'CHIC SpA.', 'company' => 'CHIC SpA.','rut' => '76879705-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Distribuidora Mechanic Shop SpA.', 'company' => 'Importadora y Distribuidora Mechanic Shop SpA.','rut' => '76346897-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Cristian Alejandro López Cáceres', 'company' => 'Cristian Alejandro López Cáceres','rut' => '13970910-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial y Distribuidora Torres y Soto Ltda.', 'company' => 'Comercial y Distribuidora Torres y Soto Ltda.','rut' => '76098040-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Lega Automotores E.I.R.L.', 'company' => 'Lega Automotores E.I.R.L.','rut' => '52004682-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Kizashi Importaciones SpA', 'company' => 'Kizashi Importaciones SpA','rut' => '77483317-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Montaña Tacull SpA', 'company' => 'Montaña Tacull SpA','rut' => '77259524-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Global Libros SpA.', 'company' => 'Global Libros SpA.','rut' => '76871279-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Petreven Chile SpA.', 'company' => 'Petreven Chile SpA.','rut' => '76101133-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Claudina del Carmen Díaz Zúñiga', 'company' => 'Claudina del Carmen Díaz Zúñiga','rut' => '10101600-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sebastián Prado y Compañía Ltda.', 'company' => 'Sebastián Prado y Compañía Ltda.','rut' => '76085387-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Gabriela Patricia Gallardo Benavides', 'company' => 'Gabriela Patricia Gallardo Benavides','rut' => '10650732-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Punta Arenas SpA.', 'company' => 'Importadora Punta Arenas SpA.','rut' => '76877104-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sea Shipping Line (Chile) SpA', 'company' => 'Sea Shipping Line (Chile) SpA','rut' => '77266068-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Granil SpA', 'company' => 'Comercial Granil SpA','rut' => '76952441-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Comercializadora y Distribuidora Oviedo Ltda.', 'company' => 'Sociedad Comercializadora y Distribuidora Oviedo Ltda.','rut' => '89327000-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'América Chile Comercializadora Ltda.', 'company' => 'América Chile Comercializadora Ltda.','rut' => '76530273-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Pedro Aliro Sánchez Barría y Cía. Ltda. o Comercial de Servicios Náuticos Limitada o Servinaut Ltda.', 'company' => 'Pedro Aliro Sánchez Barría y Cía. Ltda. o Comercial de Servicios Náuticos Limitada o Servinaut Ltda.','rut' => '77484010-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Distribuidora Raul Sosa E.I.R.L.', 'company' => 'Distribuidora Raul Sosa E.I.R.L.','rut' => '76141747-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Urzúa SpA', 'company' => 'Comercial Urzúa SpA','rut' => '77190584-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Adan Enrique Negrete Jorquera', 'company' => 'Adan Enrique Negrete Jorquera','rut' => '14301155-0'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Dante Ortiz & Compañía Limitada', 'company' => 'Dante Ortiz & Compañía Limitada','rut' => '77300385-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Guineo y Guineo Ltda.', 'company' => 'Guineo y Guineo Ltda.','rut' => '76035776-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sur Importaciones Limitada', 'company' => 'Sur Importaciones Limitada','rut' => '77629869-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Turismo Antártica XXI S.A.', 'company' => 'Turismo Antártica XXI S.A.','rut' => '99523260-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Alex Fernando Alvarez Ojeda', 'company' => 'Alex Fernando Alvarez Ojeda','rut' => '9276741-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad VS Producciones Limitada', 'company' => 'Sociedad VS Producciones Limitada','rut' => '76887337-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Autónoma Tiny Homes SpA', 'company' => 'Autónoma Tiny Homes SpA','rut' => '77581539-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Luis Arturo Cárdenas Vera', 'company' => 'Luis Arturo Cárdenas Vera','rut' => '18550931-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Antonio Cuevas y Cia. Ltda.', 'company' => 'Antonio Cuevas y Cia. Ltda.','rut' => '78144630-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Skippers SpA', 'company' => 'Skippers SpA','rut' => '77524639-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Ferro Sur Ltda.', 'company' => 'Comercial Ferro Sur Ltda.','rut' => '89719800-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Gisela Draeger Construcciones SpA.', 'company' => 'Gisela Draeger Construcciones SpA.','rut' => '77028973-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Fastcarspuq SpA.', 'company' => 'Importadora Fastcarspuq SpA.','rut' => '77692946-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Sociedad Mancilla y Mercado Cía. Ltda.', 'company' => 'Sociedad Mancilla y Mercado Cía. Ltda.','rut' => '76227647-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora H&E SpA.', 'company' => 'Importadora H&E SpA.','rut' => '77739906-3'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora Orellana Ltda.', 'company' => 'Importadora Orellana Ltda.','rut' => '88830700-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Elizabeth Mercedes Osorio Barría', 'company' => 'Elizabeth Mercedes Osorio Barría','rut' => '7425543-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Space Wise Construcción Modular SpA.', 'company' => 'Space Wise Construcción Modular SpA.','rut' => '77282058-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Guaguas & Kids SpA.', 'company' => 'Guaguas & Kids SpA.','rut' => '77381734-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Agrocentro Veterinario Compañía Limitada', 'company' => 'Agrocentro Veterinario Compañía Limitada','rut' => '89587000-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Lambda Aromaterapia y Estilo de Vida SpA.', 'company' => 'Lambda Aromaterapia y Estilo de Vida SpA.','rut' => '77763504-2'],
            // ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Inversiones Best SpA', 'company' => 'Inversiones Best SpA','rut' => '77340697-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'CSB Chile SpA.', 'company' => 'CSB Chile SpA.','rut' => '76722235-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importaciones Amari SpA', 'company' => 'Importaciones Amari SpA','rut' => '77750807-5'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Imagina SpA.', 'company' => 'Imagina SpA.','rut' => '77643894-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Goodyear de Chile S.A.C.', 'company' => 'Goodyear de Chile S.A.C.','rut' => '93770000-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Divemotor S.A.', 'company' => 'Divemotor S.A.','rut' => '79725950-0'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ernesto Cruz Urbina', 'company' => 'Ernesto Cruz Urbina','rut' => '16213427-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Compra y Venta de Joyas y Bisutería Génesis Ruiz E.I.R.L.', 'company' => 'Compra y Venta de Joyas y Bisutería Génesis Ruiz E.I.R.L.','rut' => '77789162-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Moda Austral SpA', 'company' => 'Moda Austral SpA','rut' => '77008592-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Luis Anselmo Ulloa Dominguez', 'company' => 'Luis Anselmo Ulloa Dominguez','rut' => '7094704-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Montemar Ltda.', 'company' => 'Comercial Montemar Ltda.','rut' => '76366315-9'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Festina Latam SpA.', 'company' => 'Festina Latam SpA.','rut' => '76756425-2'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'E&G Medical Systems Ltda.', 'company' => 'E&G Medical Systems Ltda.','rut' => '76089058-8'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Ingeniería y Asesorías Desarrollo Austral Ltda. o Desarrollo Austral Ltda.', 'company' => 'Ingeniería y Asesorías Desarrollo Austral Ltda. o Desarrollo Austral Ltda.','rut' => '76338909-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Constructora Bersol SpA.', 'company' => 'Constructora Bersol SpA.','rut' => '77414668-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Easybox Sur Import y Export Limitada', 'company' => 'Easybox Sur Import y Export Limitada','rut' => '77787178-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Chile Ships Services SpA.', 'company' => 'Chile Ships Services SpA.','rut' => '77077395-4'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Importadora y Comercial Tolosa y Venegas Ltda.', 'company' => 'Importadora y Comercial Tolosa y Venegas Ltda.','rut' => '76401624-6'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Grifols Chile S.A.', 'company' => 'Grifols Chile S.A.','rut' => '96582310-7'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Equipos y Servicios S.A.', 'company' => 'Comercial Equipos y Servicios S.A.','rut' => '94602000-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Juan Carlos Barria Alvarez', 'company' => 'Juan Carlos Barria Alvarez','rut' => '7490757-1'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Chelech S.A.', 'company' => 'Comercial Chelech S.A.','rut' => '76415150-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Constantino Rodrigo Santana Vera', 'company' => 'Constantino Rodrigo Santana Vera','rut' => '16065564-K'],
            ['sistem' => 'SVAWeb', 'status' => true, 'name' => 'Comercial Patagona Ltda.', 'company' => 'Comercial Patagona Ltda.','rut' => '77755610-K']
        ];

        foreach ($organizations as $organization) {
            Organization::create($organization);
        }
    }
}
